brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
edition = "2024"
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
