"""
Solution to
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fib(limit):
    res = []
    a, b, c = 1, 0, 1
    while True:
        a, b = b, c
        c = a + b
        if c > limit:
            break
        res.append(c)
    return res


sol = sum([f for f in fib(4_000_000) if f % 2 == 0])
print(sol)
