"""
Solution to
Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""


def pentagonal(i):
    return [n * (3 * n - 1) // 2 for n in range(1, i + 1)]


pentagonals = pentagonal(4000)


def find_sol():
    res = []
    for i in range(1, 3001):
        for j in range(i):
            add = pentagonals[i] + pentagonals[j]
            sub = pentagonals[i] - pentagonals[j]
            if add in pentagonals and sub in pentagonals:
                res.append(sub)
    return min(res)


sol = find_sol()
print(sol)
